sudo: false

language: python

python:
  - "2.7"

branches:
  only:
    - master

install:
  - pip install --upgrade pip
  - pip install flake8

script:
  - flake8 --benchmark --statistics
  - python setup.py bdist_egg
